[2024-04-26T16:33:42.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T16:33:42.167+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_etl_dag.cargar_datos scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-26T16:33:42.181+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_etl_dag.cargar_datos scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-26T16:33:42.188+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-04-26T16:33:42.223+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): cargar_datos> on 2024-04-22 00:00:00+00:00
[2024-04-26T16:33:42.232+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'crypto_etl_dag', 'cargar_datos', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/Crypto_etl_dag.py', '--cfg-path', '/tmp/tmpqq8dd_m2']
[2024-04-26T16:33:42.233+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask cargar_datos
[2024-04-26T16:33:42.238+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=136) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T16:33:42.239+0000] {standard_task_runner.py:63} INFO - Started process 141 to run task
[2024-04-26T16:33:42.313+0000] {task_command.py:426} INFO - Running <TaskInstance: crypto_etl_dag.cargar_datos scheduled__2024-04-22T00:00:00+00:00 [running]> on host cfc50b94fda3
[2024-04-26T16:33:42.527+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='crypto_etl_dag' AIRFLOW_CTX_TASK_ID='cargar_datos' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-26T16:33:42.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T16:33:42.542+0000] {logging_mixin.py:188} INFO - Error al cargar datos en la base de datos: 'NoneType' object has no attribute 'cursor'
[2024-04-26T16:33:42.542+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-26T16:33:42.543+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T16:33:42.557+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=crypto_etl_dag, task_id=cargar_datos, execution_date=20240422T000000, start_date=20240426T163342, end_date=20240426T163342
[2024-04-26T16:33:42.614+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-26T16:33:42.635+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T16:33:42.639+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
